### ISSUE TITLE
error: ‘Global’ has not been declared

### ISSUE THREAD

**Issue by Tsangares** [iLCSoft/Overlay#5]
Hey, I am trying to include this overlay library into my ilcsoft framework. I showed my `cmake` where to find the files using `INCLUDE_DIRECTORIES` and `AUX_SOURCE_DIRECTORY` because I do not know how get `cmake` to find the `.so` in the lib directory. 

My processor tries to include overlay with this line: `#include <Overlay>`. When I build my processor I receive this error:

`/cvmfs/ilc.desy.de/sw/x86_64_gcc44_sl6/v01-17-09/Overlay/v00-14/src/Overlay.cc:138:5: error: ‘Global’ has not been declared
     Global::EVENTSEEDER->registerProcessor(this);`

Why is `Global` not contained in the Overlay library?
Or am I missing a dependency with `Global` in it?

Or am I supposed to include the shared library with cmake? 

You guys are the architects of my world, I greatly appreciate and admire what you guys do, thank you so much.

**Comment by gaede** [comment]
Overlay is a library with Marlin processors. There should be not need to include Overlay.h in another Marlin processor ( and it will most likely break things). What do you actually want to do ?
Maybe we can suggest a better way of achieving this...

**Comment by Tsangares** [comment]
What I actually want to do is take a couple collections of events and merge them into one collection using a unique Poisson distribution for each collection.

Once I have this collection, my group and I will look for the signatures of the events and try to predict what type of events are occurring in the combined event. 

The overlay class has this `expBG` parameter that looks like exactly what I wanted.

**Comment by Tsangares** [comment]
I learned how to run your processor, I am new to marlin. I will consult my group to help me with the rest.

Although, I have a number of `.list` with contain new line delimited list of `.slcio` files. Does your `InputFileNames` parameter take `.list` filetypes?

**Comment by Tsangares** [comment]
I have a more precise question and important question than the previous: 
I am trying to take the events in `test.slcio` and output them, but I have no idea where they are going to output. 
Here is my steering file:
`<?xml version="1.0" encoding="us-ascii"?>



<marlin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ilcsoft.desy.de/marlin/marlin.xsd">
  <execute>
    <processor name="bruce">
    </processor>
  </execute>
  <global>
        <parameter name="RandomSeed" value="1234567890" />
  </global>

  <processor name="bruce" type="Overlay">
    <parameter name="InputFileNames">test.slcio</parameter>
    <parameter name="NumberOverlayEvents" type="int">2</parameter>
    <parameter name="CollectionMap">mcParticles mcParticlesBG</parameter>
    <parameter name="runOverlay" type="bool">true</parameter>
  </processor>
</marlin>`

This is the output I get:
`[ WARNING "Marlin"]  ---- no GEAR XML file given  --------- 
[ MESSAGE "bruce"] 
[ MESSAGE "bruce"] ---- bruce -  parameters: 
[ MESSAGE "bruce"] 	CollectionMap:  mcParticles mcParticlesBG 
[ MESSAGE "bruce"] 	InputFileNames:  test.slcio 
[ MESSAGE "bruce"] 	NSkipEventsRandom:  0
[ MESSAGE "bruce"] 	NumberOverlayEvents:  2
[ MESSAGE "bruce"] 	expBG:  1
[ MESSAGE "bruce"] 	runOverlay:  true
[ MESSAGE "bruce"] -------------------------------------------------
[ DEBUG6 "bruce"] *** opened files for overlay - first file : test.slcio    has 200560  events. 
[ DEBUG6 "bruce"]     will use direct access from 200560  events. 
[ DEBUG "bruce"] ProcessorEventSeeder: srand initialised with global seed 1234567890
[ DEBUG "bruce"] ProcessorEventSeeder: Processor bruce registered for random seed service. Allocated 1727406014 as initial seed.
[ WARNING4 "bruce"] Using runOverlay, NumberOverlayEvents and expBG get ignored.
[ WARNING4 "bruce"]  -----------   
[ WARNING4 "bruce"]  the following processor will modify the LCIO event :  bruce !! 
[ WARNING4 "bruce"]  ------------  
[ MESSAGE "bruce"]  ------------------------------------------    Overlay processor 0 background events on 0 physics events.
[ MESSAGE "bruce"]       -> mean = -nan  ±  -nan
[ MESSAGE "bruce"] 
[ MESSAGE "Marlin"]  --------------------------------------------------------- 
[ MESSAGE "Marlin"]   Events skipped by processors : 
[ MESSAGE "Marlin"]   Total: 0
[ MESSAGE "Marlin"]  --------------------------------------------------------- 
[ MESSAGE "Marlin"] 
[ MESSAGE "Marlin"]  --------------------------------------------------------- 
[ MESSAGE "Marlin"]       Time used by processors ( in processEvent() ) :      
[ MESSAGE "Marlin"] 
[ MESSAGE "Marlin"] bruce                                0.000000e+00 s in            0 events  ==>          NaN [ s/evt.] 
[ MESSAGE "Marlin"]             Total:                   0.000000e+00 s in            0 events  ==>          NaN [ s/evt.] 
[ MESSAGE "Marlin"]  --------------------------------------------------------- `

Where does this processors output an slcio, or it is just going to change test.slcio?

**Comment by Tsangares** [comment]
Hi, I had a lot of problems, but I have figured it all out. I have to say, the pdf & readme were not explicit enough for me use the Overlay lib. I spent a lot of hours in the past 2 weeks trying to interpret with the limited resources I was given. I am not trying to scold, I am wondering how I can help make it more clear and usable for the next person?

Also, once the Overlay processor is done with the events, where does the output slcio go?

Some things to add to the readme: 
- Brief Instructions on how to run the processor on Marlin. I had to set `MARLIN_DLL` to the `libOverlay.so` after I build the library.
- Maybe put the example steering file on here, I know it is explained in the PDF but this is more clear (I put it in the next comment.)
- Also the hurdle was the realization that the global parameter of `LCIOInputFiles` which takes an `.slcio` has to be set as the signal file.

If all of this is conveyed somewhere else, could you please link to it on the readme?

Is all of this assumed knowledge from Marlin?

How do I access `LCIOTOOLS`, I could really use them?

**Comment by Tsangares** [comment]
After the command `export MARLIN_DLL=/path_to/Overlay/lib/libOverlay.so` then the command `Marlin -x` gives an output with this snippet:
```
<processor name="MyOverlayEvents" type="OverlayEvents">
 <!--Merge a number of events in a LCIO file into 1 event-->
  <!--Name of collections will be merged-->
  <parameter name="MergedCollectionNames" type="StringVec">VXDCollection SITCollection SETCollection FTDCollection  </parameter>
  <!--Name of the lcio output file-->
  <parameter name="OutputFileName" type="string">overlayEvent.slcio </parameter>
  <!--verbosity level of this processor ("DEBUG0-4,MESSAGE0-4,WARNING0-4,ERROR0-4,SILENT")-->
  <!--parameter name="Verbosity" type="string">DEBUG </parameter-->
</processor>
```

Important information that maybe should be more easily accessed.
